import Stripe from "stripe";
import type { ApplicationPack } from "@/lib/types";

export const runtime = "nodejs";

// Verify the A$19 Application Pack session was paid before we'll send anything —
// keeps this from being used as an open email relay.
async function isPaid(sessionId: string): Promise<boolean> {
  if (!process.env.STRIPE_SECRET_KEY) return false;
  try {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    return (
      session.status === "complete" &&
      (session.payment_status === "paid" || session.payment_status === "no_payment_required") &&
      session.metadata?.product === "application-pack"
    );
  } catch {
    return false;
  }
}

// ─── Rate limiting ───────────────────────────────────────────────────────────
const WINDOW_MS = 60_000;
const MAX_REQUESTS = 3;
const hits = new Map<string, { count: number; resetAt: number }>();

function isRateLimited(ip: string): boolean {
  const now = Date.now();
  const entry = hits.get(ip);
  if (!entry || now > entry.resetAt) {
    hits.set(ip, { count: 1, resetAt: now + WINDOW_MS });
    return false;
  }
  entry.count++;
  return entry.count > MAX_REQUESTS;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function buildHtml(pack: ApplicationPack): string {
  const h = (t: string) =>
    `<h2 style="font-family:Georgia,serif;color:#10243e;font-size:18px;margin:28px 0 8px">${esc(t)}</h2>`;
  const role = `${esc(pack.role.title)}${pack.role.company ? ` — ${esc(pack.role.company)}` : ""}`;

  const tweaks = pack.cvTweaks
    .map(
      (t) =>
        `<li style="margin-bottom:10px"><strong>${esc(t.after)}</strong>${
          t.note ? `<br><span style="color:#64748b;font-size:13px">${esc(t.note)}</span>` : ""
        }</li>`
    )
    .join("");

  const questions = pack.interviewQuestions
    .map(
      (q) =>
        `<li style="margin-bottom:10px"><strong>${esc(q.question)}</strong><br><span style="color:#475569">${esc(
          q.angle
        )}</span></li>`
    )
    .join("");

  const keywords = pack.atsKeywords.map((k) => esc(k)).join(" · ");
  const tips = pack.applicationTips.map((t) => `<li style="margin-bottom:6px">${esc(t)}</li>`).join("");
  const letter = esc(pack.coverLetter)
    .split(/\n\s*\n/)
    .map((p) => `<p style="margin:0 0 12px;line-height:1.6">${p.replace(/\n/g, "<br>")}</p>`)
    .join("");

  return `<div style="max-width:640px;margin:0 auto;font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1e293b;padding:8px 4px">
  <p style="color:#0f9b8e;font-weight:700;font-size:13px;letter-spacing:1px;text-transform:uppercase;margin:0">Application Pack</p>
  <h1 style="font-family:Georgia,serif;color:#10243e;font-size:22px;margin:4px 0 0">${role}</h1>
  ${h("Your positioning")}<p style="line-height:1.6;margin:0">${esc(pack.fitSummary)}</p>
  ${h("Cover letter")}${letter}
  ${h("Tailored CV bullets")}<ul style="padding-left:18px;margin:0">${tweaks}</ul>
  ${h("Keywords to include")}<p style="color:#0f766e;line-height:1.8;margin:0">${keywords}</p>
  ${h("Likely interview questions")}<ul style="padding-left:18px;margin:0">${questions}</ul>
  ${h("Tips for this application")}<ul style="padding-left:18px;margin:0">${tips}</ul>
  <hr style="border:none;border-top:1px solid #e2e8f0;margin:28px 0 12px">
  <p style="color:#94a3b8;font-size:12px;line-height:1.6">Generated by <a href="https://dropmycv.app" style="color:#0f9b8e">dropmycv.app</a>. We don't store your CV or this pack — this email is the only copy we sent, to the address you gave us. Good luck!</p>
</div>`;
}

export async function POST(request: Request) {
  try {
    const ip =
      request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
      request.headers.get("x-real-ip") ||
      "unknown";
    if (isRateLimited(ip)) {
      return Response.json({ error: "Too many requests — please wait a minute." }, { status: 429 });
    }

    if (!process.env.RESEND_API_KEY) {
      return Response.json(
        { error: "Email isn't configured yet — please use the download instead." },
        { status: 503 }
      );
    }

    const body = await request.json();
    const { email: rawEmail, pack, sessionId } = body as {
      email?: string;
      pack?: ApplicationPack;
      sessionId?: string;
    };

    const email = typeof rawEmail === "string" ? rawEmail.trim().slice(0, 200) : "";
    if (!EMAIL_RE.test(email)) {
      return Response.json({ error: "That doesn't look like a valid email." }, { status: 400 });
    }
    if (!pack || typeof pack !== "object" || !pack.role?.title || !pack.coverLetter) {
      return Response.json({ error: "Nothing to send." }, { status: 400 });
    }
    if (!sessionId || !(await isPaid(String(sessionId)))) {
      return Response.json({ error: "Payment required." }, { status: 402 });
    }

    const from = process.env.PACK_EMAIL_FROM || "dropmycv <noreply@dropmycv.app>";
    const subject = `Your Application Pack — ${pack.role.title}`.slice(0, 120);

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ from, to: [email], subject, html: buildHtml(pack) }),
    });

    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      console.error("[email-pack] resend error:", res.status, detail.slice(0, 300));
      return Response.json({ error: "Couldn't send the email — please use the download." }, { status: 502 });
    }

    return Response.json({ sent: true });
  } catch (err) {
    console.error("[email-pack] error:", err);
    return Response.json({ error: "Something went wrong." }, { status: 500 });
  }
}
