"use client";

import { useState } from "react";
import { trackEvent } from "@/lib/analytics";
import type { ApplicationPack } from "@/lib/types";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Self-contained printable HTML document (used for both download & print-to-PDF),
// so the deliverable looks clean regardless of the page it came from.
function buildDoc(pack: ApplicationPack): string {
  const role = `${esc(pack.role.title)}${pack.role.company ? ` — ${esc(pack.role.company)}` : ""}`;
  const letter = esc(pack.coverLetter)
    .split(/\n\s*\n/)
    .map((p) => `<p>${p.replace(/\n/g, "<br>")}</p>`)
    .join("");
  const tweaks = pack.cvTweaks
    .map((t) => `<li><strong>${esc(t.after)}</strong>${t.note ? `<br><em>${esc(t.note)}</em>` : ""}</li>`)
    .join("");
  const questions = pack.interviewQuestions
    .map((q) => `<li><strong>${esc(q.question)}</strong><br><span>${esc(q.angle)}</span></li>`)
    .join("");
  const tips = pack.applicationTips.map((t) => `<li>${esc(t)}</li>`).join("");
  const keywords = pack.atsKeywords.map((k) => esc(k)).join(" · ");

  return `<!doctype html><html><head><meta charset="utf-8"><title>Application Pack — ${role}</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1e293b;max-width:720px;margin:40px auto;padding:0 24px;line-height:1.6}
  .kicker{color:#0f9b8e;font-weight:700;font-size:12px;letter-spacing:1.5px;text-transform:uppercase;margin:0}
  h1{font-family:Georgia,serif;color:#10243e;font-size:26px;margin:4px 0 4px}
  h2{font-family:Georgia,serif;color:#10243e;font-size:18px;margin:30px 0 8px;border-bottom:1px solid #e2e8f0;padding-bottom:4px}
  em{color:#64748b;font-style:normal;font-size:14px}
  .kw{color:#0f766e}
  ul{padding-left:20px} li{margin-bottom:10px}
  .foot{color:#94a3b8;font-size:12px;margin-top:36px;border-top:1px solid #e2e8f0;padding-top:12px}
  @media print{body{margin:0;max-width:none}}
</style></head><body>
  <p class="kicker">Application Pack</p>
  <h1>${role}</h1>
  <h2>Your positioning</h2><p>${esc(pack.fitSummary)}</p>
  <h2>Cover letter</h2>${letter}
  <h2>Tailored CV bullets</h2><ul>${tweaks}</ul>
  <h2>Keywords to include</h2><p class="kw">${keywords}</p>
  <h2>Likely interview questions</h2><ul>${questions}</ul>
  <h2>Tips for this application</h2><ul>${tips}</ul>
  <p class="foot">Generated by dropmycv.app — we don't store your CV or this pack, so keep this copy. Good luck!</p>
</body></html>`;
}

export function ApplicationPackResult({
  pack,
  sessionId,
}: {
  pack: ApplicationPack;
  sessionId: string;
}) {
  const [email, setEmail] = useState("");
  const [emailState, setEmailState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [emailMsg, setEmailMsg] = useState("");

  function download() {
    const blob = new Blob([buildDoc(pack)], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const safe = pack.role.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 40) || "role";
    a.download = `application-pack-${safe}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function printPack() {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(buildDoc(pack));
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 300);
  }

  async function sendEmail() {
    if (emailState === "sending") return;
    setEmailState("sending");
    setEmailMsg("");
    try {
      const res = await fetch("/api/email-pack", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, pack, sessionId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Couldn't send.");
      setEmailState("sent");
      trackEvent("pack_emailed");
    } catch (err) {
      setEmailState("error");
      setEmailMsg(err instanceof Error ? err.message : "Couldn't send.");
    }
  }

  const role = `${pack.role.title}${pack.role.company ? ` — ${pack.role.company}` : ""}`;

  return (
    <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold text-teal-ink uppercase tracking-widest">Application Pack</p>
          <h3 className="text-xl font-serif font-bold text-navy mt-0.5">{role}</h3>
        </div>
        <div className="flex gap-2">
          <button
            onClick={printPack}
            className="text-sm font-semibold px-4 py-2 rounded-lg bg-navy text-white hover:bg-navy-dark transition-colors"
          >
            🖨 Print / Save as PDF
          </button>
          <button
            onClick={download}
            className="text-sm font-semibold px-4 py-2 rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50 transition-colors"
          >
            ⬇ Download
          </button>
        </div>
      </div>

      <Section title="Your positioning">
        <p className="text-slate-600 leading-relaxed">{pack.fitSummary}</p>
      </Section>

      <Section title="Cover letter">
        <div className="rounded-xl bg-slate-50 border border-slate-100 p-4 space-y-3">
          {pack.coverLetter.split(/\n\s*\n/).map((p, i) => (
            <p key={i} className="text-sm text-slate-700 leading-relaxed whitespace-pre-line">
              {p}
            </p>
          ))}
        </div>
      </Section>

      {pack.cvTweaks.length > 0 && (
        <Section title="Tailored CV bullets">
          <ul className="space-y-3">
            {pack.cvTweaks.map((t, i) => (
              <li key={i} className="text-sm">
                <p className="text-slate-700 font-medium leading-relaxed">{t.after}</p>
                {t.note && <p className="text-slate-500 text-xs mt-0.5">{t.note}</p>}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {pack.atsKeywords.length > 0 && (
        <Section title="Keywords to include">
          <div className="flex flex-wrap gap-1.5">
            {pack.atsKeywords.map((k) => (
              <span key={k} className="text-xs font-medium text-teal-ink bg-teal-light px-2.5 py-1 rounded-full">
                {k}
              </span>
            ))}
          </div>
        </Section>
      )}

      {pack.interviewQuestions.length > 0 && (
        <Section title="Likely interview questions">
          <ul className="space-y-3">
            {pack.interviewQuestions.map((q, i) => (
              <li key={i} className="text-sm">
                <p className="text-slate-700 font-medium">{q.question}</p>
                <p className="text-slate-500 leading-relaxed mt-0.5">{q.angle}</p>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {pack.applicationTips.length > 0 && (
        <Section title="Tips for this application">
          <ul className="list-disc pl-5 space-y-1.5 text-sm text-slate-600">
            {pack.applicationTips.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </Section>
      )}

      {/* Optional email — privacy default is download; this only fires if they ask */}
      <div className="pt-4 border-t border-slate-100">
        {emailState === "sent" ? (
          <p className="text-sm text-emerald-700">✓ Sent to {email}. We don&apos;t keep a copy.</p>
        ) : (
          <div>
            <p className="text-sm text-slate-500 mb-2">
              Want a copy emailed too? Optional — we only use this address to send this pack, then it&apos;s gone.
            </p>
            <div className="flex flex-wrap gap-2">
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="flex-1 min-w-[200px] text-sm border border-slate-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-teal focus:border-transparent"
              />
              <button
                onClick={sendEmail}
                disabled={emailState === "sending"}
                className="text-sm font-semibold px-4 py-2 rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50 transition-colors disabled:opacity-50"
              >
                {emailState === "sending" ? "Sending…" : "Email me a copy"}
              </button>
            </div>
            {emailState === "error" && <p className="text-xs text-rose-500 mt-1.5">{emailMsg}</p>}
          </div>
        )}
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h4 className="text-sm font-semibold text-navy uppercase tracking-wide mb-2">{title}</h4>
      {children}
    </div>
  );
}
