import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — dropmycv",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-100 px-6 py-4">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="text-2xl font-extrabold tracking-tight transition-colors group">
            <span className="text-indigo-600">drop</span><span className="text-slate-800 group-hover:text-indigo-600">mycv</span><span className="text-indigo-600">.app</span>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-slate-800 mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-10">Last updated: June 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-600 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">1. Acceptance of terms</h2>
            <p>
              By using dropmycv (&ldquo;the Service&rdquo;), you agree to these Terms of Service.
              If you do not agree, do not use the Service. dropmycv is operated by an Australian
              individual (ABN to be added) and is governed by the laws of Queensland, Australia.
            </p>
            <p className="mt-3">
              You must be at least 18 years old to use dropmycv.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">2. Description of service</h2>
            <p>
              dropmycv is a free job matching tool. You upload a CV, the Service extracts your
              skills and experience profile using AI, searches for relevant live job listings via
              third-party APIs, and returns a ranked shortlist. The Service is provided for
              informational purposes only.
            </p>
            <p className="mt-3">
              dropmycv does not guarantee employment, does not act as a recruitment agency, and
              does not represent any employer. All job listings displayed are sourced from
              third-party job boards and are subject to those platforms&apos; terms and availability.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">3. No professional advice</h2>
            <p>
              dropmycv is an automated search tool, not a professional service. Nothing on this
              website constitutes career, recruitment, legal, financial, or any other kind of
              professional advice. Any decision you make based on the Service&apos;s output —
              including whether to apply for a role — is entirely your own.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">4. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-3 space-y-2">
              <li>Upload files containing malicious code or content designed to harm the Service</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service&apos;s APIs</li>
              <li>Use the Service for any unlawful purpose or in violation of any applicable law</li>
              <li>Upload content belonging to another person without their consent</li>
              <li>Systematically make automated requests to the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">5. AI-generated results</h2>
            <p>
              Job matches are generated by AI and are provided &ldquo;as is&rdquo; without any
              guarantee of accuracy, completeness, or suitability. AI systems can make errors.
              You should independently verify any job listing before applying and exercise your
              own judgement about suitability.
            </p>
            <p className="mt-3">
              dropmycv does not warrant that results are free from bias. Rankings are based on
              AI assessment of textual similarity between your CV and job descriptions and do
              not constitute a recommendation of any individual for any role.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">6. Privacy</h2>
            <p>
              Our handling of your information is described in our{" "}
              <Link href="/privacy" className="text-indigo-600 hover:underline">
                Privacy Policy
              </Link>
              . In short, we do not store the information you submit. Your CV is read locally
              in your browser, contact details are stripped before transmission, and extracted
              text is forwarded to third-party services solely to return job results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">7. Affiliate disclosure</h2>
            <p>
              dropmycv participates in affiliate programmes. When you click &ldquo;Apply Now&rdquo;
              on a job listing, you may be directed to a third-party website via a tracked link.
              dropmycv may earn a referral fee if you proceed to apply for or interact with that
              listing. This does not affect the cost to you in any way, and affiliate
              relationships do not influence the ranking of results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">8. Intellectual property</h2>
            <p>
              The dropmycv name, logo, and website design are the property of the operator.
              You retain all rights to your CV and its contents. By uploading your CV, you grant
              dropmycv a temporary, limited licence to process it solely for the purpose of
              generating job match results during your session.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, dropmycv and its operator are not liable
              for any direct, indirect, incidental, or consequential loss arising from your use
              of the Service, including but not limited to: reliance on AI-generated job matches,
              missed employment opportunities, or any action taken by a third-party employer or
              job board.
            </p>
            <p className="mt-3">
              Where liability cannot be excluded by law, it is limited to re-supplying the
              Service or the cost of doing so.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">10. Australian Consumer Law</h2>
            <p>
              Nothing in these Terms excludes, restricts, or modifies any consumer guarantee,
              right, or remedy you have under the Australian Consumer Law or any other law that
              cannot lawfully be excluded. If you are a consumer under the Australian Consumer
              Law, you have guarantees that operate alongside these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">11. Third-party links</h2>
            <p>
              Job listings link to third-party websites. dropmycv has no control over, and
              accepts no responsibility for, the content, privacy practices, or terms of those
              websites. Accessing a third-party site is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">12. Changes to the Service</h2>
            <p>
              dropmycv reserves the right to modify, suspend, or discontinue the Service at any
              time without notice. We may also update these Terms from time to time. The
              &ldquo;last updated&rdquo; date at the top of this page indicates when these Terms
              last changed. Continued use of the Service after changes are posted constitutes
              your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">13. Governing law</h2>
            <p>
              These Terms are governed by the laws of Queensland, Australia. Any disputes
              arising from these Terms or your use of dropmycv will be subject to the exclusive
              jurisdiction of the courts of Queensland.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">14. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:legal@dropmycv.app" className="text-indigo-600 hover:underline">
                legal@dropmycv.app
              </a>
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-slate-100 py-5 text-center text-xs text-slate-300 mt-12">
        <Link href="/" className="hover:text-slate-500 transition-colors">← Back to dropmycv</Link>
        <span className="mx-3">·</span>
        <Link href="/privacy" className="hover:text-slate-500 transition-colors">Privacy Policy</Link>
      </footer>
    </div>
  );
}
